name: macos-multi-arch-build

on: [push, pull_request]

jobs:
  macos-build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        architecture: ['arm64', 'x86_64']  # Build for both architectures

    steps:
      - name: Sync repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rosetta 2 (Only for x86_64)
        if: matrix.architecture == 'x86_64'
        run: |
          softwareupdate --install-rosetta --agree-to-license

      - name: Install Dependencies
        run: |
          arch -${{ matrix.architecture }} brew update
          arch -${{ matrix.architecture }} brew install mosquitto zeromq

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: '${{ github.workspace }}/qt_installation/'
          key: ${{ runner.os }}-QtCache-${{ matrix.architecture }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: '5.15.2'
          host: 'mac'
          arch: '${{ matrix.architecture }}'
          dir: '${{ github.workspace }}/qt_installation/'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          aqtversion: '==3.1.17'
          py7zrversion: '==0.22.0'

      - name: Build PlotJuggler for ${{ matrix.architecture }}
        shell: bash
        run: |
          arch -${{ matrix.architecture }} cmake -B build -DCMAKE_INSTALL_PREFIX=install -DCMAKE_OSX_ARCHITECTURES=${{ matrix.architecture }} PlotJuggler
          arch -${{ matrix.architecture }} cmake --build build --target install

      - name: Archive Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: PlotJuggler-${{ matrix.architecture }}
          path: build
